# LAB 1

<!-- 1.	Create 2 variables, ‘A’ and ‘B’, perform the 4 operations on them.
2.	Create 2 array, ‘A’ and ‘B’, perform the 4 operations on each of their elements.
3.	Add the 2 arrays from previous question, with the single array left, find its sum, mean and variance.
4.	Create a file with 2 variables ‘x’ and ‘y’, using file handling operations. Find sum of all x^2 variables and y^2 variables.
 -->

1.	Create 2 variables, ‘A’ and ‘B’, perform the 4 operations on them.
2.	Create 2 array, ‘A’ and ‘B’, perform the 4 operations on each of their elements.
3.	Add the 2 arrays from previous question, with the single array left, find its sum, mean and variance.
4.	Create a file with 2 variables ‘x’ and ‘y’, using file handling operations. Find sum of all x^2 variables and y^2 variables.


# LAB 2

## MINI CALCULATOR USING CLASSES IN PYTHON

In [1]:

class mini_cal:
    def __init__(self,a,b):
        self.a = a
        self.b = b
        self.add = a + b
        self.sub = a - b
        self.multi = a * b
        self.div = a / b
        
    def addition(self):
        ## This method is used to find the sum of two numbers
        print("\nThe sum of two numbers is : {}\n".format(self.add))
    
    def subtract(self):
        ## This method is used to find the difference of two numbers
        print("The difference of two numbers is : {}\n".format(self.sub))
        
    def multiply(self):
        ## This method is used to multiply two numbers
        print("the product of two numbers is : {}\n".format(self.multi))
    
    def division(self):
        ## This method is used to divide two numbers
        print("The division of two numbers is : {}\n".format(self.div))
    

In [ ]:
# print("The following are the simple calculations on two numbers :")
a = int(input("Enter the first number : "))
b = int(input("Enter the second number : "))
cal = mini_cal(a, b)

for i in range(1,5):
    choice = int(input("Enter the choice from 1 to 4 :"))
    
    if(choice == 1):
        cal.addition()
        
    if(choice == 2):
        cal.subtract()
        
    if(choice == 3):
        cal.multiply()
        
    if(choice == 4):
        cal.division()
    else:
        pass

Enter the first number :  5
Enter the second number :  2
Enter the choice from 1 to 4 : 1



The sum of two numbers is : 7



# LAB 3


<img src = "lab3 assignment.jpeg"/>

#### IMPORTING THE LIBRARIES REQUIRED

In [28]:
import numpy as np
import matplotlib.pyplot as plt

# CREATING THE RANDOM ARRAY

In [29]:
# creating a random array of size 64*64 in the range 0-255 (inclusive)

def create_array():
    """
    This function will create an array of user defined number of rows and columns.
    """
    import random 
    np.random.seed(42)
    rows = int(input("Enter the number of rows: "))
    columns = int(input("Enter the number of columns: "))
    
    array = np.random.randint(0, 256, size=(rows,columns))
    
    print(array)
    print(type(array))
    print(array.shape)
    print(array.size)
    print(array.ndim)
    
    return array

# SLICING THE ARRAY AND CREATING COLUMN VECTORS

In [30]:
def split_the_list(array):
    """
    This function will split the array into its column vectors and return a list where each element of the list is the column vector of the array.
    """
    array_split = []
    for i in range(0,array.shape[0]):
        vector = array[:,[i]]
        array_split.append(vector)
    return array_split

# PLOTTING THE FUNCTIONS

In [31]:
def plotting(list_of_array, x_label, y_label, plot_title):
    %matplotlib inline
    """
    let's plot the mean of all the vectors
    """ 
    plt.plot(list_of_array, color='green', linestyle='dashed', linewidth = 0.5, 
             marker='o', markerfacecolor='blue', markersize=4)
    plt.xlabel(x_label)
    plt.ylabel(x_label)
    plt.title('MEAN OF ALL THE ARRAYS')
    plt.figure(figsize=(200,200), edgecolor = 'black', );

# MEAN

In [32]:
def mean(array_split_list):
    
    """
    This function finds the mean of each vector in our list and returns a list containing the mean of individual vectors in our list.
    """
    
    #creating an empty list
    mean_list = []
    
    length_of_list   = len(array_split_list)
    length_of_vector = len(array_split_list[0])
    
    for i in range(0,length_of_list):
        SUM = 0
        vector = array_split_list[i]
        
        for j in range(0,length_of_vector):
            SUM = SUM + vector[j]
            
        mean = float(SUM/length_of_vector)
        mean_list.append(mean)
        
    a = input("DO U WANT A GRAPHICAL REPRESENTATION OF ALL THE MEANS. YES/NO?\n")
    while(True):
        if(a == 'YES' or a == 'yes'):
            plotting(variance_without_using_inbuilt_function, 'VECTORS', 'MEANS', 'MEANS OF ALL THE VECTORS')
            break
        elif(a == 'NO' or a =='no'):
            break
        else:
            print("Enter YES/NO")
    return mean_list
    

# L2-NORM

In [33]:
# L2 Norm is just the lenth of the vector in the Euclidean space.

# Now let's write a function to find the L2 norm of the individual vectors in the list
import math
def L2_norm(array_split):
    """
    This function returns the distance between two vectors in the euclidean space.
    """
    print("Let's find L2-norm between two variables.\n")
    v1 = int(input("Enter the first choice: "))
    v2 = int(input("Enter the second choice: "))
    
    vector1 = array_split[v1]
    vector2 = array_split[v2]
    
    vector3 = vector1 - vector2
    
    SUM = 0
    for i in range(0,vector3.shape[0]):
        square = vector3[i]**2
        SUM = SUM + square
    
    l2_norm = SUM ** 0.5
    return float(l2_norm)

# VARIANCE

In [34]:

def variance_without_using_inbuilt_function(array_split,mean_list):
    """
    Calculates the variance
    """
    variance_without_using_inbuilt_function = []
    for i in range(0,64):
        
        vector2 = array_split[i]
        
        vector2_mean = mean_list[i]
        
        vector2_minus_mean = vector2 - vector2_mean
        
        vector2_minus_mean_abs = np.abs(vector2_minus_mean)

        vector2_minus_mean_abs_sqaure = vector2_minus_mean_abs **2
        
        SUM = 0
        for j in range(0,vector2_minus_mean_abs_sqaure.shape[0]):
            SUM = SUM + vector2_minus_mean_abs_sqaure[j]
        vector2_minus_mean_abs_sqaure_mean = float(SUM/vector2_minus_mean_abs_sqaure.shape[0])
 
        variance_without_using_inbuilt_function.append(vector2_minus_mean_abs_sqaure_mean)
    
    
    a = input("DO U WANT A GRAPHICAL REPRESENTATION OF ALL THE VARIANCES. YES/NO?\n")
    while(True):
        if(a == 'YES' or a == 'yes'):
            plotting(variance_without_using_inbuilt_function, 'VECTORS', 'VARIANCE', 'VARIANCE OF ALL THE VECTORS')
            break
        elif(a == 'NO' or a =='no'):
            break
        else:
            print("Enter YES/NO")
            
    
    return variance_without_using_inbuilt_function

# MULTIPLY ANY TWO VECTORS

In [35]:
def multiply_any_two_vectors(array_split):
    """
    This function will take the input as any two vectors and print their product.
    """
    print("Let's multiply two vectors.\n")
    v1 = int(input("Enter the first choice: "))
    v2 = int(input("Enter the first choice: "))
    
    vector1 = array_split[v1]
    vector2 = array_split[v2]
    
    print(vector1*vector2)
    

# COVARIANCE

In [36]:
def covariance_1(A1_split, mean_list):
    """
    This function finds the covarince between two column vectors os the matrix
    """
    print("Let's find the covariance of two numbers")
    v1 = int(input("Enter the first choice: "))
    v2 = int(input("Enter the second choice: "))

    vector1 = A1_split[v1]
    vector2 = A1_split[v2]
    
    # While finding the covariance we find the expectation of the vector but in this case, each element of the vector has equal propability of occurance. so mean = expectation.
    vector1_mean = mean_list[v1]
    vector2_mean = mean_list[v2]
    
    vector1_minus_mean = vector1 - vector1_mean
    vector2_minus_mean = vector2 - vector2_mean
    
    vector3 = vector1_minus_mean * vector2_minus_mean
    
    length = vector3.shape[0]
    SUM = 0
    for i in range(0,length):
        SUM = SUM + vector3[i]
    Covariance = float(SUM/length)
        
    return Covariance
    

In [37]:
def covariance_2(array_split, mean_list):
    """
    This function finds the covarince between two column vectors of the matrix
    """
    v1 = int(input("Enter the first choice: "))
    v2 = int(input("Enter the second choice: "))

    vector1 = array_split[v1]
    vector2 = array_split[v2]
    
    vector1_mean = mean_list[v1]
    vector2_mean = mean_list[v2]
    
    vector3 = vector1 * vector2
    
    SUM = 0
    for i in range(0,vector3.shape[0]):
        SUM = SUM + vector3[i]
    vector3_mean = SUM/vector3.shape[0]
    
    vector4 = vector1_mean * vector2_mean
    
    covariance = vector3_mean - vector4
        
    return covariance, v1, v2
    

# CORRELATION CO-EFFECIENT

In [38]:
def correlation_coeffecient(array_split, mean_list, variance_list):
    """
    This function will return the correlation coeffecient between two variables.
    """
    print("Let's find Correlation between two vectors.\n")
    covariance, v1, v2 = covariance_2(array_split,mean_list)
    std1 = variance_list[v1] ** 0.5 
    std2 = variance_list[v2] ** 0.5
    
    correlation = covariance/(std1 * std2)
    
    vector1 = np.reshape(array_split[v1], newshape=(array_split[v1].shape[0]))
    vector2 = np.reshape(array_split[v2], newshape=(array_split[v2].shape[0]))
    
    print(np.corrcoef(vector1, vector2))
    return correlation

# GRAPH

In [39]:
def histogram_and_pdf(A1):

    column_major_array = A1.reshape((64*64),1)
    
    range_of_array = list(range(0,column_major_array.shape[0]))
    
    
    fig, (ax1, ax2) = plt.subplots(nrows=1,
                                   ncols=2,
                                   figsize=(14,3))
    ax1.hist(column_major_array, bins=256,  histtype='step', label='HISTOGRAM', color='red', density=False);
    
    ax2.hist(column_major_array, bins=256,  histtype='step', label='HISTOGRAM', color='Blue', density=True);
    

In [40]:
def scatterplot(array):
    """
    This fucntion will print the scatter plot.
    """
    rows = array.shape[0]
    columns = array.shape[1]
    
    column_major_array = array.reshape((rows*columns),1)
    
    range_of_array = list(range(0,column_major_array.shape[0]))
    
    fig, ax1 = plt.subplots(nrows=1,
                               ncols=1,
                               figsize=(14,3))
    ax1.scatter(range_of_array, column_major_array, marker='.', color = 'orange')

### MAIN FUNCTION

In [41]:
def main():
    """
    Main function.
    """
    print("To begin with, Let's first create an array.")
    A1 = create_array()
    
    ("Now array columns will be extracted and stored in the list!")
    A1_split = split_the_list(A1)
    
    test = True
    while(test):
        choice = int(input("Please enter your choice:\n1 for Mean of a vector\n2 for Variance of a vector\n3 for Covariance between two vectors\n4 for Correlation between two vecotrs\n5 for L2-norm\n6 to Multiply two vectors\n7 Scatter Plot\n8 Histogram and Pdf\n9 to EXIT\t"))
        
        if(choice == 1):
            A1_mean_list = mean(A1_split)
            option = int(input("Enter the vector number for whch you want ot find the mean:\t"))
            print(A1_mean_list[option])
            
        elif(choice == 2):
            A1_var_list = variance_without_using_inbuilt_function(A1_split,A1_mean_list)
            option = int(input("Enter the vector number for whch you want ot find the variance:\t"))
            print(A1_var_list[option])
            
        elif(choice == 3):
            A1_covar = covariance_1(A1_split,A1_mean_list)
            print(A1_covar)
            
        elif(choice == 4):
            A1_corr = correlation_coeffecient(A1_split, A1_mean_list, A1_var_list)
            print(A1_corr)
            
        elif(choice == 5):
            A1_l2_norm = L2_norm(A1_split)
            print(A1_l2_norm)
            
        elif(choice == 6):
            multiply_any_two_vectors(A1_split)
            
        elif(choice == 7):
            scatterplot(A1)
        
        elif(choice == 8):
            histogram_and_pdf(A1)
        
        elif(choice == 9):
            break
        

In [43]:
if __name__=="__main__": 
    main() 

To begin with, Let's first create an array.
Enter the number of rows: 64
Enter the number of columns: 64
[[102 179  92 ... 134  20  72]
 [166  17 131 ...  23 153 216]
 [251 187 123 ... 141 102  26]
 ...
 [250 219 250 ... 191   4  99]
 [ 69  89   3 ... 177 160 218]
 [  6  69 126 ... 166  85 176]]
<class 'numpy.ndarray'>
(64, 64)
4096
2
Please enter your choice:
1 for Mean of a vector
2 for Variance of a vector
3 for Covariance between two vectors
4 for Correlation between two vecotrs
5 for L2-norm
6 to Multiply two vectors
7 Scatter Plot
8 Histogram and Pdf
9 to EXIT	9
